openapi: 3.0.4
info:
  title: API de Contatos
  description: Aplicação para gerenciamento de contatos de pessoa e organizações
  contact:
    name: Daniel de Sousa
    email: daniel@servidor.net
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://localhost:5500
    variables: {}
    description: Servidor Local
tags:
  - name: Pessoas
    description: Controle de pessoas
paths:
  /pessoas:
    summary: Manipular informações relacionadas às pessoas da aplicação
    get:
      tags:
        - Pessoas
      summary: Listar pessoas cadastradas
      description: 'Retorna um array de pessoas'
      operationId: listaPessoas
      parameters:
        - in: query
          name: search
          description: Texto a ser procurado no nome das pessoas
          schema:
            type: string
        - in: query
          name: order
          description: Critério de ordenação dos resultados (ascendente | descedente)
          schema:
            type: string
            enum:
              - asc
              - desc
        - in: query
          name: tags
          description: Tags a serem procuradas nas pessoas cadastradas
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Pessoa'
    post:
      tags:
        - Pessoas
      summary: Cadastrar pessoa
      operationId: inserePessoa
      requestBody:
        description: Pessoa a ser inserida
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pessoa'
        required: true
      responses:
        '201':
          description: Recurso inserido com sucesso
  /pessoas/{idPessoa}:
    get:
      tags:
          - Pessoas
      summary: Obter uma pessoa específica por meio do ID
      parameters:
        - in: path
          required: true
          name: idPessoa
          schema:
            type: integer
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pessoa'
        '404':
          description: Pessoa não encontrada
    put:
      tags:
        - Pessoas
      summary: Alterar uma pessoa específica por meio do ID
      operationId: alteraPessoa
      parameters:
        - in: path
          required: true
          name: idPessoa
          schema:
            type: integer
      responses:
        '204':
          description: Recurso alterado com sucesso
        '400':
          description: Erro ao alterar o recurso no servidor
    delete:
      summary: Alterar uma pessoa específica por meio do ID
      tags:
        - Pessoas
      parameters:
        - in: path
          required: true
          name: idPessoa
          schema:
            type: integer
      responses:
        '204':
          description: Recurso excluído com sucesso
        '400':
          description: Erro ao excluir o recurso no servidor
  /pessoas/{tag}:
    get:
      tags:
        - Pessoas
      summary: Listar pessoas cadastradas
      parameters:
        - in: path
          required: true
          name: tag
          schema:
            type: string
      operationId: listaPessoasPorTag
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pessoa'

components:
  schemas:
    Pessoa:
      type: object
      properties:
        id: 
          type: integer
        nome:
          type: string
          description: Nome do contato
        email:
          type: string
          description: E-mail do contato
        telefone:
          type: string
          description: Número de telefone do contato
        organizacao:
          $ref: '#/components/schemas/Organizacao'
        tags:
          type: array
          description: Grupos aos quais o contato está associado
          items:
            type: string
      required:
        - nome
        - email
      example: 
        id: 5
        nome: Francis Ford Copolla
        email: copolla@hollywood.com
        telefone: 001-124-2111
        organizacao: 
          id: 1
          nome: Acme Corporation
          segmento: Varejo
          endereco: Av. Rebolças, 422 - Centro
          cidade: São Paulo 
          cep: 33422-990
          estado: SP
          telefones: ["11-3234-5543", "11-4425-5544"]
        tags: ["cinema", "trabalho"]
    Organizacao:
      title: Organizacao
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        segmento:
          type: string
        endereco:
          type: string
        cidade:
          type: string
        cep:
          type: string
        estado:
          type: string
        telefones:
          type: array
          items:
            type: string
      required:
        - nome
        - segmento
      example: 
        id: 1
        nome: Acme Corporation
        segmento: Varejo
        endereco: Av. Rebolças, 422 - Centro
        cidade: São Paulo 
        cep: 33422-990
        estado: SP
        telefones: ["11-3234-5543", "11-4425-5544"]